migrate to compilefree 18.1 version
also propagate term signal through children to make container stopping faster and fix double execution on container restart

big thanks to @Celedhrim for the xpra approach

diff --git a/kodi_init b/kodi_init
--- a/kodi_init
+++ b/kodi_init
@@ -1,18 +1,20 @@
 #!/bin/bash
+
 set -e
+trap 'kill $(jobs -p)' EXIT
 
-echo -e "\nStarting container...\n======================================================="
+cp /usr/local/share/kodi/advancedsettings.xml.default /config/userdata/advancedsettings.xml
+chown kodi. /config/userdata/advancedsettings.xml
 
-cp /config/.kodi/userdata/advancedsettings.xml.default /config/.kodi/userdata/advancedsettings.xml
-chown kodi. /config/.kodi/userdata/advancedsettings.xml
+echo "======================================================="
 
 if [ ! -z $KODI_DBHOST ] && [ ! -z $KODI_DBUSER ] && [ ! -z $KODI_DBPASS ]; then
   echo "Shared MySQL database: YES"
-  sed -i -e "s/\(<host>\)\([^<]*\)\(<[^>]*\)/\1$KODI_DBHOST\3/g" /config/.kodi/userdata/advancedsettings.xml
-  sed -i -e "s/\(<user>\)\([^<]*\)\(<[^>]*\)/\1$KODI_DBUSER\3/g" /config/.kodi/userdata/advancedsettings.xml
-  sed -i -e "s/\(<pass>\)\([^<]*\)\(<[^>]*\)/\1$KODI_DBPASS\3/g" /config/.kodi/userdata/advancedsettings.xml
-  sed -i -e "s/\(<type>\)\([^<]*\)\(<[^>]*\)/\1mysql\3/g" /config/.kodi/userdata/advancedsettings.xml
-  sed -i -e "s/\(<port>\)\([^<]*\)\(<[^>]*\)/\13306\3/g" /config/.kodi/userdata/advancedsettings.xml
+  sed -i -e "s/\(<host>\)\([^<]*\)\(<[^>]*\)/\1$KODI_DBHOST\3/g" /config/userdata/advancedsettings.xml
+  sed -i -e "s/\(<user>\)\([^<]*\)\(<[^>]*\)/\1$KODI_DBUSER\3/g" /config/userdata/advancedsettings.xml
+  sed -i -e "s/\(<pass>\)\([^<]*\)\(<[^>]*\)/\1$KODI_DBPASS\3/g" /config/userdata/advancedsettings.xml
+  sed -i -e "s/\(<type>\)\([^<]*\)\(<[^>]*\)/\1mysql\3/g" /config/userdata/advancedsettings.xml
+  sed -i -e "s/\(<port>\)\([^<]*\)\(<[^>]*\)/\13306\3/g" /config/userdata/advancedsettings.xml
 else
   echo "Shared MySQL database: NO"
 fi
@@ -45,11 +47,11 @@ update_library_job &
 echo "Automatic library update: YES (${KODI_UPDATE_INTERVAL}s)"
 
 if [[ $KODI_CLEAN == "yes" ]] || [[ $KODI_CLEAN == "true" ]]; then
-  if [ -e /config/.kodi/userdata/sources.xml ]; then
+  if [ -e /config/userdata/sources.xml ]; then
     echo "Automatic library cleaning: YES (${KODI_CLEAN_INTERVAL}s)"
     clean_library_job &
   else
-    echo "Automatic library cleaning: NO (/config/.kodi/userdata/sources.xml not found)"
+    echo "Automatic library cleaning: NO (/config/userdata/sources.xml not found)"
   fi
 else
   echo "Automatic library cleaning: NO"
@@ -57,5 +59,12 @@ fi
 
 echo "======================================================="
 
-tail -F -q /config/.kodi/temp/kodi.log 2> /dev/null &
-su kodi -c "kodi --headless"
+echo "Starting Kodi..."
+if [ -f /config/temp/kodi.log ]; then
+  rm /config/temp/kodi.log
+fi
+if [ -f /tmp/.X100-lock ]; then
+  rm /tmp/.X100-lock
+fi
+tail -F -q /config/temp/kodi.log 2> /dev/null &
+exec su kodi -c "xpra start :100 --daemon=no --exit-with-children --start-child='kodi -p --standalone' > /dev/null 2>&1"
